sonar.projectKey=tirumala
sonar.projectName=Tirumala
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=**/vendor/**,**/runtime/**,**/assets/**,**/tests/**,**/web/assets/**

sonar.language=php
sonar.sourceEncoding=UTF-8

sonar.host.url=http://192.168.1.100:9000
