<?php

return [
    'adminEmail' => 'admin@example.com',
    'eiplDirPath' => 'D:/ftp/eipl/',
    'unionBankDirPath' => 'C:/unionbank/',
    'biplDirPath' => 'C:/BIPLFTP/',
    'rateFilesPath' => 'web/ratechart',
    'biplRateUtilityPath' => 'web/utility/BIPL/Rate',
    'biplMemberUtilityPath' => 'web/utility/BIPL/Vendor',
    'jasper_server' => 'http://localhost:13099/jasperserver',
    'jasper_username' => 'jasperadmin',
    'jasper_password' => 'Jasper@PCDF$2017',
    'report_path' => '/Reports/',
    'dpu_docs_path' => 'web/uploads/dpu-docs/',
    'complaint_dir_path' => 'web/uploads/complaint-docs/',
    'collection_dir_path' => '/web/collection-data/',
    'logo_path' => '/themes/pcdf/assets/images/union_logo/',
    'temp_logo_path' => '/web/import/image/',
    'crystal_report_path' => '\modules\crystalreports\reports',
    'notification_url' => 'https://fcm.googleapis.com/fcm/send',
    'everest_notification_key' => 'AAAA2-vGiKw:APA91bH6ktJ0IRHSyIYqToe5OoUh5IJp2w5yVoNvqGc3AZtTjgTdRyDa9fbcLkyp6PCVfh03S9-2Si7e6ofwnZ_vv0OCPD4uTsKAxPci6mA-06630U5ydXMRqca0eFEcMz4CCw0bwlyi',
    'bmc_notification_key' => 'AAAAwaXvLGk:APA91bFt_cBNfXsVl6L6U4RiZrlotbQQyxvKBmsxGnxHUI8LI23FMf4hEntk52_1Gwxi7z9rC22e-3j89tzYz47v8lrw8aVbeCSU0bej719usgK8JgB3LJw81BS87IrquCEpQ76cELAS',
    'member_notification_key'=>'AAAAbdLVu64:APA91bEdjAOomODXEbjtGr74P5-NQDpN3FnlVPg9tzyf8SChLTkUDz1wtv8tHYj0OjeU1DZhpq0BBD81twAjbZlAVJNJ3ogpIYsQCJZ1cN1Xr9fgfZD6ASdHirmOIatOfqRH52u0AyBf',
    'projectPath' => 'E:\Apache24\htdocs\tirumala',
    'convert_crystal_report_path' => 'web\utility\CrystalReportsNinja-master\Deployment',
    'rptHtmlPath' => '\modules\crystalreports\html',
    'ho_notification_key'=>'AAAATsR3lJw:APA91bEDDapzfO1L7c-7MAV3lxLElNHpf2rHCZrj2dDOUF4io3zCzi1gUS5DcusK3SqPYMecucn7t2YXOP_k5_0eGfSgj34fhxz0T1vsGpXAc30lOXVK_l5d-EW28gA_EIF-rtn3jSBB',
    'vendorApiErrorLogPath' => 'C:/THIRUMALA/VendorAPI/ErrorLogs',
];
