<?php

namespace app\modules\import;

/**
 * import module definition class
 */
class importData extends \yii\base\Module {

    /**
     * @inheritdoc
     */
    public $controllerNamespace = 'app\modules\import\controllers';

    /**
     * @inheritdoc
     */
    public function init() {
        parent::init();

        // custom initialization code goes here
    }

    public static function getLabels($l) {
        $label = [
            'addressbook' => ['table_name' => 'tbl_addressbook', 'fields' => 'id,destinations,flag_entry,organization_code,organization_type,source_org_type,sync_url,table_name,to_child,to_parent,type', 'default_fields' => ''],
            'state' => ['table_name' => 'tbl_states', 'fields' => 'state_code,state_name,local_name,is_active'],
            'district' => ['table_name' => 'tbl_districts', 'fields' => 'district_code,district_name,local_name', 'scenario' => 'importCsv', 'default_fields' => 'is_active:1'],
            'sub-district' => ['table_name' => 'tbl_sub_districts', 'fields' => 'sub_district_code,sub_district_name,district_code,local_name', 'default_fields' => 'is_active:1'],
            'village' => ['table_name' => 'tbl_villages', 'fields' => 'village_code,village_name,sub_district_code,local_name', 'default_fields' => 'is_active:1'],
            'hamlet' => ['import_class' => 'hamlet_import', 'table_name' => 'tbl_hamlets', 'fields' => 'hamlet_name,village_code,local_name', 'scenario' => 'importCsv', 'default_fields' => 'is_active:1'],
            'village-miscellaneous' => ['table_name' => 'tbl_village_miscellaneous', 'fields' => 'village_miscellaneous_code,miscellaneous_code,village_code,description,local_description,is_active',],
            //'village-miscellaneous'=>['table_name'=>'tbl_village_miscellaneous','fields'=>'village_miscellaneous_code,miscellaneous_code,village_code,description,local_name','default_fields'=>'is_active:1','is_child_import'=>true,'child_table_name'=>'tbl_village_miscellaneous_local','child_field_name'=>['village_miscellaneous_code'=>'village_miscellaneous_code','description'=>'description'],'child_default_field'=>'is_active:1'],
            'TblMiscellaneous' => ['table_name' => 'tbl_miscellaneous', 'fields' => 'miscellaneous_name,local_name', 'default_fields' => 'is_active:1', 'increment' => 1],
            'TblDcsTypes' => ['table_name' => 'tbl_dcs_types', 'fields' => 'dcs_type_name,local_name', 'default_fields' => 'is_active:1', 'increment' => 1],
            'TblCasteCategory' => ['table_name' => 'tbl_caste_category', 'fields' => 'caste_category_name,local_name', 'default_fields' => 'is_active:1', 'increment' => 1],
            'unit' => ['table_name' => 'tbl_units', 'fields' => 'unit_name,local_name,short_name,local_short_name', 'default_fields' => 'is_active:1', 'increment' => 1],
            'animal-type' => ['table_name' => 'tbl_animal_type', 'fields' => 'animal_type_name,local_name,short_name,is_milch', 'default_fields' => 'is_active:1', 'increment' => 1],
            'milk-quality-type' => ['table_name' => 'tbl_milk_quality_type', 'fields' => 'milk_quality_type_name,local_name', 'default_fields' => 'is_active:1', 'increment' => 1],
            'land-unit' => ['table_name' => 'tbl_land_unit', 'fields' => 'land_unit_name,local_name,land_unit,conversion_factor', 'scenario' => 'importCsv', 'default_fields' => 'is_active:1', 'increment' => 1],
            'capacity' => ['table_name' => 'tbl_capacity', 'fields' => 'value', 'default_fields' => 'is_active:1', 'increment' => 1],
            'vehicle_type' => ['table_name' => 'tbl_vehicle_type', 'fields' => 'vehicle_type_name,local_name', 'default_fields' => 'is_active:1', 'increment' => 1],
            'bank' => ['table_name' => 'tbl_banks', 'fields' => 'ac_no_length,bank_name,local_name,checked_ac_no,nationalized_bank', 'default_fields' => 'is_active:1', 'scenario' => 'importCsv', 'mapping' => 1, 'mapping_model' => 'TblBanksDistrictsMapping', 'mapping_fields' => 'bank_code,district_code'],
            'branch' => ['import_class' => 'branch_import', 'table_name' => 'tbl_branch', 'fields' => 'bank_code,branch_name,local_name,ifsc,hamlet_code,address,local_address,pincode', 'default_fields' => 'is_active:1', 'scenario' => 'importCsv'],
            'federation' => ['table_name' => 'tbl_federations', 'fields' => 'federation_code,federation_name,federation_code_ex,registration_no,registration_date,state_code,district_code,sub_district_code,village_code,hamlet_code,city,address,pincode,phone_no,contact_person,contact_person_email,contact_person_mobile_no,contact_person_pan_no,contact_person_phone_no,fax_no,bank_code,branch_code,bank_account_no,ifsc', 'default_fields' => 'is_active:1'],
            'union' => ['import_class' => 'union_import', 'table_name' => 'tbl_unions', 'fields' => 'federation_code,union_name,local_name,union_short_name,union_code_ex,registration_no,registration_date,hamlet_code,city,address,local_address,pincode,phone_no,fax_no,contact_person_pan_no,upi_no,gst_no', 'scenario' => 'importCsv', 'default_fields' => 'is_active:1'],
            'route' => ['table_name' => 'tbl_routes', 'fields' => 'union_code,route_code,route_name,vehicle_type_code,route_length_kms,capacity,start_time,return_time', 'default_fields' => 'is_active:1'],
            'dcs' => ['import_class' => 'dcs_import', 'import_main_class' => 'DcsImportStrategy', 'table_name' => 'tbl_dcs', 'fields' => 'union_code,bmc_code,dcs_code_ex,ref_code,dcs_name,local_name,dcs_short_name,local_short_name,address,local_address,hamlet_code,milk_type_code,pincode,effective_date,phone_no,upi_no,dcs_type_code,pan_no,registration_code,registration_date,is_dispatch_mandate,is_weight_manual,is_quality_manual,credit_sale_allow,vendor,dpu_type,rate_chart_member,contact_person,local_contact_person,middle_name,local_middlename,surname,local_surname,email,mobile_no,department,ifsc,bank_account_no', 'default_fields' => 'originating_type:1', 'scenario' => 'importCsv', 'update_key' => 'ref_code,union_code', 'exclude_update' => 'union_code,bmc_code,rate_chart_member', 'mapping' => 1, 'mapping_model' => 'TblDcsMilkType', 'mapping_fields' => 'dcs_code,milk_type_code'],
            'member' => ['import_class' => 'member_import', 'table_name' => 'tbl_member', 'import_main_class' => 'BackGroundDataImportStrategy', 'fields' => 'dcs_code,ex_member_code,ref_code,member_name,local_name,father_name,local_father_name,surname,local_surname,nominee_name,local_nominee_name,nominee_relation,dob,bloodgroup_code,gender_code,qualification_code,caste_category_code,religion_code,total_land,animal_type_code,no_of_buffalo,no_of_cow_cross,no_of_cow_ind,member_type_code,branch_code,bank_account_no,beneficiary_name,mobile_no,email,address,local_address,pincode,pan_no,adhar_no,annual_income,hamlet_code,voter_id,member_class,registration_date,max_allowed_qty', 'scenario' => 'importCsv', 'default_fields' => 'upload:1,is_active:1', 'update_key' => 'dcs_code,ex_member_code,union_code', 'exclude_update' => 'dcs_code,ex_member_code,ref_code', 'historyClass' => 'TblMemberHistory'],
            'member_limited' => ['import_main_class' => 'MemberImportStrategy', 'table_name' => 'tbl_member', 'fields' => 'member_name,local_name,mobile_no,bank_name,branch_name,bank_account_no,ifsc,adhar_no', 'scenario' => 'importLimitedCsv', 'default_fields' => 'is_active:1,upload:1'],
            'sub-center' => ['import_class' => 'sub_center_import', 'import_main_class' => 'SubCenterImportStrategy', 'table_name' => 'tbl_sub_center', 'fields' => 'dcs_code,sub_center_code,sub_center_name,is_bmc,destination_type,destination_code,address,hamlet_code,route_code,pincode,phone_no,contact_person,contact_person_mobile_no,contact_person_email,branch_code,bank_account_no,ifsc,upi_no,is_main_dcs', 'default_fields' => 'is_active:1', 'scenario' => 'importCsv', 'mapping' => 1, 'mapping_model' => 'TblSubCenterMilkType', 'mapping_fields' => 'sub_center_code,milk_type_code'],
            'collection_point' => ['table_name' => 'tbl_collection_point', 'fields' => 'federation_code,union_code,dcs_code,sub_center_code,collection_point_no,is_default', 'default_fields' => 'is_active:1', 'scenario' => 'importCsv'],
            'mcc-plant' => ['import_class' => 'mcc_plant_import', 'import_main_class' => 'CommonImportStrategy', 'table_name' => 'tbl_mcc_plant', 'fields' => 'union_code,plant_code,mcc_plant_code_ex,ref_code,name,local_name,description,hamlet_code,is_weight_manual,is_quality_manual,gst_no', 'default_fields' => 'is_active:1', 'scenario' => 'importCsv', 'mapping' => 1, 'mapping_model' => 'TblMccMilkType', 'mapping_fields' => 'mcc_plant_code,milk_type_code'],
            'plant' => ['import_class' => 'plant_import', 'import_main_class' => 'CommonImportStrategy', 'table_name' => 'tbl_plant', 'fields' => 'union_code,plant_code_ex,ref_code,name,local_name,description,hamlet_code', 'default_fields' => 'is_active:1', 'scenario' => 'importCsv'],
            'bmc' => ['import_class' => 'bmc_import', 'table_name' => 'tbl_bmc', 'fields' => 'union_code,mcc_plant_code,bmc_code_ex,ref_code,bmc_type_code,bmc_name,local_name,model,capacity,manufacturer_code,bmc_milk_type,hamlet_code,is_weight_manual,is_quality_manual', 'default_fields' => 'is_active:1', 'scenario' => 'importCsv', 'mapping' => 1, 'mapping_model' => 'TblBmcMilkType', 'mapping_fields' => 'bmc_code,milk_type_code'],
            'transporter' => ['import_class' => 'transporter_import', 'table_name' => 'tbl_transporter', 'fields' => 'transporter_name,local_name,address,contact_person,email,mobile_no,bank_code,branch_code,bank_account_no,ifsc,adhar_no,union_code,hamlet_code', 'default_fields' => 'is_active:1', 'scenario' => 'importCsv', 'increment' => 1],
            'ledger-group' => ['table_name' => 'tbl_ledger_group', 'fields' => 'ledger_group_name,ledger_type_code', 'default_fields' => 'is_active:1', 'increment' => 1],
            'ledger' => ['table_name' => 'tbl_ledger', 'fields' => 'union_code,ledger_group_code,ledger_name,entry_type,has_sub_ledger', 'default_fields' => 'is_active:1'],
            'sub-ledger' => ['table_name' => 'tbl_sub_ledger', 'fields' => 'union_code,sub_ledger_code,sub_ledger_name,reference_code,type', 'default_fields' => 'is_active:1'],
            'asset-group' => ['table_name' => 'tbl_asset_group', 'fields' => 'asset_group_name', 'default_fields' => 'is_active:1', 'increment' => 1],
            'asset-sub-group' => ['table_name' => 'tbl_asset_sub_group', 'fields' => 'union_code,asset_sub_group_code,asset_sub_group_name,asset_group_code', 'default_fields' => 'is_active:1'],
            'union-bill-head' => ['table_name' => 'tbl_union_bill_head', 'fields' => 'union_code,union_bill_head_name,union_bill_head_code,sequence_no', 'default_fields' => 'is_active:1'],
            'tax-group' => ['table_name' => 'tbl_tax_group', 'fields' => 'tax_group_name', 'default_fields' => 'is_active:1', 'increment' => 1],
            'tax' => ['table_name' => 'tbl_tax', 'fields' => 'tax_group_code,tax_code,tax_name', 'default_fields' => 'is_active:1'],
            'basic-tax' => ['table_name' => 'tbl_basic_tax', 'fields' => 'basic_tax_name', 'default_fields' => 'is_active:1', 'increment' => 1],
            'financial-year' => ['table_name' => 'tbl_financial_year', 'fields' => 'starting_date,ending_date,code', 'default_fields' => 'is_active:1'],
            'incometax-dep-per' => ['table_name' => 'tbl_asset_depreciation_incometax_act', 'fields' => 'percentage,type,asset_group_code,financial_year_code', 'default_fields' => 'is_active:1', 'increment' => 1],
            'rate-formula' => ['table_name' => 'tbl_formula', 'fields' => 'formula_code,formula_description,formula,wef_date,dcs_code,milk_type_code,rate_type_code,union_code', 'default_fields' => 'is_active:1'],
            'union-payment-cycle' => ['table_name' => 'tbl_union_payment_cycle', 'fields' => 'union_payment_cycle_code,from_date,from_shift,interval_value,is_billing,lock_billing_process,to_date,to_shift,union_code', 'default_fields' => 'is_active:1'],
            'member-classification' => ['table_name' => 'tbl_member_classification', 'fields' => 'member_classification_name,local_name,member_classification_type,range_from,range_to,union_code', 'default_fields' => 'is_active:1', 'scenario' => 'importCsv'],
            'general-union-config' => ['table_name' => 'tbl_union_config', 'fields' => 'union_config_code,perc_disp_recp_milk,min_member_age,manual_days_collection,audit_response_time,auto_audit_resolution,range_end,union_code', 'default_fields' => 'is_active:1'],
            'product-group' => ['table_name' => 'tbl_product_group', 'fields' => 'product_group_code,product_group_name', 'default_fields' => 'is_active:1'],
            'product' => ['table_name' => 'tbl_product', 'fields' => 'product_code,product_name', 'default_fields' => 'is_active:1'],
            'product-purchase-rate' => ['table_name' => 'tbl_product_purchase_rate', 'fields' => 'purchase_code,purchase_rate', 'default_fields' => 'is_active:1'],
            'interfacing-device' => ['table_name' => 'tbl_interfacing_device', 'fields' => 'interfacing_device_code,baud_rate,bit_rate,device_name,device_type,discard_char,end_char,incoming_data_type,is_snf,length,parity,reading_type,reg_expression,split_char,start_char,stop_bit,tare,device_manufacturer_id,union_code', 'default_fields' => 'is_active:1'],
            'milk_dispatch' => ['import_main_class' => 'DispatchImportStrategy', 'table_name' => 'tbl_milk_dispatch', 'fields' => 'mcc_code,dcs_code,date_time_of_collection,shift,qty,fat,snf,no_of_can,return_cob,remarks', 'scenario' => 'importCsv'],
            'dpu-incentive' => ['import_class' => 'tbl_dpu_incentive_master', 'import_main_class' => 'DpuIncentiveImportStrategy', 'table_name' => 'tbl_dpu_incentive_master', 'fields' => 'union_code,dcs_code,m_start_time,e_start_time,m_cutoff_time,e_cutoff_time,m_lock_time,e_lock_time,inc_rate,inc_deduction'],
            'bmc-collection' => ['table_name' => 'tbl_bmc_collection', 'fields' => 'bmc_code,bmc_silos_info_code,date_time_of_collection,shift_code,customer_type,customer_code,sample_no,milk_type_code,milk_quality_type_code,qty,fat,snf,rtpl,amount,collection_type,transporter_code,vehicle_code,route_arrival_time', 'default_fields' => 'is_active:1,originating_type:1', 'scenario' => 'importCsv', 'update_key' => 'bmc_code,customer_code,customer_type,date_time_of_collection,shift_code,sample_no', 'exclude_update' => 'bmc_code,customer_code,customer_type,date_time_of_collection,shift_code,sample_no', 'historyClass' => 'TblBmcCollectionHistory'],
            'customer-master' => ['table_name' => 'tbl_customer_master', 'fields' => 'bmc_code,route_code,customer_type,customer_code_ex,ref_code,customer_name,local_name,address,local_address,gst_no,same_milk_type,diff_milk_type,hamlet_code,contact_person,local_contact_person,middle_name,local_middlename,surname,local_surname,email,mobile_no,department,ifsc,bank_account_no', 'default_fields' => 'is_active:1', 'scenario' => 'importCsv', 'save_child' => true, 'update_key' => 'ref_code,union_code', 'exclude_update' => 'customer_code,union_code,bmc_code,customer_type', 'historyClass' => 'TblCustomerMasterHistory'],
            'dpu-password' => ['import_class' => 'TblDpuPasswords', 'mapping' => '0', 'mapping_model' => 'TblDpuPasswords', 'import_main_class' => 'DpuPasswordImportStrategy', 'table_name' => 'TblDpuPasswords', 'fields' => 'dcs_code,AdminPwd,SuperPwd,UserPwd', 'scenario' => 'importCsv'],
            'milk-collection' => ['table_name' => 'tbl_milk_collection', 'fields' => 'bmc_code,dcs_code,member,date_time_of_collection,shift_code,sample_no,milk_type_code,qty,fat,snf,rtpl,amount', 'default_fields' => 'is_active:1,originating_type:1', 'scenario' => 'importCsv', 'update_key' => 'dcs_code,member_code,date_time_of_collection,shift_code,sample_no', 'exclude_update' => 'bmc_code,dcs_code,member_code,date_time_of_collection,shift_code,sample_no', 'save_child' => true, 'historyClass' => 'TblMilkCollectionHistory'],
            'bill-head-detail' => ['import_class' => 'tbl_bill_head_detail', 'import_main_class' => 'BillHeadDetailImportStrategy', 'table_name' => 'tbl_bill_head_detail', 'fields' => 'bmc_code,customer_type,customer_code,transaction_date,bill_head_code,amount,no_installment', 'default_fields' => 'is_active:1,originating_type:1', 'scenario' => 'importCsv'],
            'vsp-outstanding' => ['table_name' => 'tbl_vsp_outstanding', 'fields' => 'bmc_code,customer_type,customer_code,transaction_date,hold_amount,due_amount', 'default_fields' => 'originating_type:1', 'scenario' => 'importCsv'],
            'member-bill-head-detail' => ['import_class' => 'tbl_bill_head_detail', 'import_main_class' => 'BillHeadDetailImportStrategy', 'table_name' => 'tbl_bill_head_detail', 'fields' => 'bmc_code,dcs_code,member_code,transaction_date,bill_head_code,amount,no_installment', 'default_fields' => 'is_active:1,originating_type:1', 'scenario' => 'importDetailCsv'],
            'staff-member' => ['import_class' => 'tbl_staff_member', 'table_name' => 'tbl_staff_member', 'fields' => 'union_code,ex_staff_member_code,staff_member_name,department,birth_date,blood_group_code,gender_code,qualification_code,caste_category_code,designation_code,branch_code,bank_account_no,mobile_no,email_id,tenure_from_date,is_on_role,uan_no,esic_no,pf_no,payment_mode,address,pincode,pan_no,aadhar_card_no,hamlet_code', 'save_child' => true, 'scenario' => 'importCsv', 'default_fields' => 'originating_type:1,is_active:1', 'increment' => 1],
            'staff-add-deduction' => ['import_class' => 'tbl_staff_addition_deduction', 'table_name' => 'tbl_staff_addition_deduction', 'fields' => 'staff_member_code,tr_date,type,app_from_date,amount,installment_no', 'save_child' => true, 'scenario' => 'importCsv', 'default_fields' => 'originating_type:1,is_active:1', 'increment' => 1],
            'member-provisional' => ['table_name' => 'tbl_member_provisional', 'fields' => 'dcs_code,ex_member_code,member_name,local_name,father_name,local_father_name,surname,local_surname,nominee_name,local_nominee_name,nominee_relation,dob,bloodgroup_code,gender_code,qualification_code,caste_category_code,religion_code,total_land,animal_type_code,no_of_buffalo,no_of_cow_cross,no_of_cow_ind,member_type_code,branch_code,bank_account_no,mobile_no,email,address,local_address,pincode,pan_no,adhar_no,annual_income,hamlet_code,voter_id,member_class,registration_date', 'default_fields' => 'upload:1,is_active:1', 'scenario' => 'importCsv'],
            'route-master' => ['import_class' => 'tbl_route_mapping',
                'table_name' => 'tbl_route_mapping',
                'fields' => 'union_code,route_code_ex,ref_code,route_name,route_type,to_type,to_dest,capacity,vehicle_type_code,route_length_kms,morning_grace_time,evening_grace_time,morning_start_time,morning_end_time,evening_start_time,evening_end_time,firstname,mobile_no', 'save_child' => true, 'scenario' => 'importCsv', 'mapping' => 1, 'mapping_model' => 'TblRouteMappingSources', 'mapping_fields' => 'route_code,customer_type,customer_code', 'mapping_scenario' => 'importMapping', 'save_map_child' => TRUE],
            'milk-dispatch' => ['table_name' => 'tbl_dcs_milk_dispatch_txn', 'fields' => 'bmc_code,dcs_code,date_time_of_dispatch,shift_code,milk_type_code,milk_quality_type_code,dispatch_qty,avg_fat,avg_snf,rtpl,total_amount', 'save_child' => true, 'old_label' => ['dispatch_qty', 'avg_fat', 'avg_snf', 'total_amount'], 'new_label' => ['qty', 'fat', 'snf', 'amount'], 'default_fields' => 'originating_type:1', 'scenario' => 'importCsv'],
            'asset-master' => ['table_name' => 'tbl_asset_master', 'fields' => 'asset_group_code,asset_code,asset_name,local_name,cmpl_product_code,is_serial_number', 'default_fields' => 'is_active:1', 'scenario' => 'importCsv'],
            'store-location' => ['table_name' => 'tbl_store_location', 'fields' => 'union_code,store_location_name,local_name,store_location_type,reference_code,sloc_code', 'default_fields' => 'is_active:1', 'increment' => 1, 'scenario' => 'importCsv'],
            'asset-group' => ['table_name' => 'tbl_asset_group', 'fields' => 'union_code,asset_group_code,asset_group_name,local_name,reference_code', 'default_fields' => 'is_active:1'],
            'asset-detail' => ['import_class' => 'tbl_asset_transaction', 'import_main_class' => 'AssetDetailImportStrategy', 'table_name' => 'tbl_asset_detail', 'fields' => 'asset_code,sap_code,serial_number,qty,make,from_type,from_sloc,to_type,to_sloc,capacity,purchase_date,transaction_date,warranty_period,maintanance_duration_in_days,in_use', 'default_fields' => 'is_active:1', 'increment' => 1, 'scenario' => 'importCsv'],
            'vehicle-master' => ['table_name' => 'tbl_vehicle_master', 'fields' => 'transporter_code,vehicle_code,parsing_no,vehicle_type_code,fuel_type_code,capacity_code,registration_no,applicable_rto,wef_date,pollution_certificate,expiry_date,insurance,rc_book_no,rent,average,billing_method,driver_name,driver_contact_no,driving_license_number', 'default_fields' => 'is_active:1', 'increment' => 1, 'scenario' => 'importCsv', 'update_key' => 'vehicle_code', 'exclude_update' => 'vehicle_code', 'historyClass' => 'TblVehicleMasterHistory'],
            'vehicle-km-info' => ['table_name' => 'tbl_vehicle_km_info', 'fields' => 'vehicle_code,route_code,wef_date,shift_code,morning_kms,evening_kms', 'default_fields' => 'is_active:1', 'scenario' => 'importCsv'],
            'vehicle-extra-km' => ['table_name' => 'tbl_vehicle_extra_km_daywise', 'fields' => 'vehicle_code,date,extra_kms', 'default_fields' => 'is_active:1', 'scenario' => 'importCsv'],
            'fuel-rate' => ['table_name' => 'tbl_fuel_rate_master', 'fields' => 'bmc_code,fuel_type_code,rate,wef_date', 'scenario' => 'importCsv'],
            'transporter-master' => ['table_name' => 'tbl_transporter', 'fields' => 'union_code,transporter_code,transporter_name,local_name,registration_no,address,phone_no,gstin,beneficiary_name,hamlet_code,tds_per,pan_no,agreement_no,declaration,security_cheque_no,security_amount,contact_person,local_contact_person,middle_name,local_middlename,surname,local_surname,email,mobile_no,department,ifsc,bank_account_no', 'default_fields' => 'is_active:1', 'scenario' => 'importCsv', 'update_key' => 'transporter_code', 'exclude_update' => 'transporter_code,union_code,hamlet_code', 'save_child' => true, 'historyClass' => 'TblTransporterHistory'],
            'km-wise-rate' => ['table_name' => 'tbl_km_wise_rate', 'fields' => 'union_code,parsing_no,rate,from_km,to_km,wef_date', 'scenario' => 'importCsv'],
            'bmc-collection-bulk' => ['table_name' => 'tbl_bulk_data_import', 'import_main_class' => 'BulkImportStrategy', 'fields' => 'bmc_code,bmc_silos_info_code,date_time_of_collection,shift_code,customer_type,customer_code,sample_no,milk_type_code,milk_quality_type_code,qty,fat,snf,rtpl,amount,collection_type,vehicle_code,route_arrival_time', 'scenario' => 'bmc_collection'],
            'milk-collection-bulk' => ['table_name' => 'tbl_bulk_data_import', 'import_main_class' => 'BulkImportStrategy', 'fields' => 'bmc_code,dcs_code,member_code,date_time_of_collection,shift_code,sample_no,milk_type_code,qty,fat,snf,rtpl,amount', 'scenario' => 'milk_collection'],
            'member-bulk' => ['import_class' => 'back_ground_data_import', 'import_main_class' => 'BulkImportStrategy', 'table_name' => 'back_ground_data_import', 'fields' => 'dcs_code,ex_member_code,ref_code,member_name,local_name,father_name,local_father_name,surname,local_surname,nominee_name,local_nominee_name,nominee_relation,dob,bloodgroup_code,gender_code,qualification_code,caste_category_code,religion_code,total_land,animal_type_code,no_of_buffalo,no_of_cow_cross,no_of_cow_ind,member_type_code,branch_code,bank_account_no,beneficiary_name,mobile_no,email,address,local_address,pincode,pan_no,adhar_no,annual_income,hamlet_code,voter_id,member_class,registration_date,max_allowed_qty', 'scenario' => 'member', 'default_fields' => 'upload:1,is_active:1'],
        ];
        return $label[$l];
    }

}
