<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    ' Invalid Ifsc Code.' => '',
    ' You have entered invalid ifsc code. e.g. "SBIN0005748".' => '',
    ' You have entered invalid pancard number. e.g. "AAAPL1234C".' => '',
    'Bank account no must contain ' => '',
    'Bank cannot be blank' => '',
    'Can not use range in between of used range.' => '',
    'District cannot be blank' => '',
    'From Qty and To Qty cannot be same.' => '',
    'From Qty cannot be less then To Qty.' => '',
    'Grade Name has been already taken.' => '',
    'Hamlet cannot be blank' => '',
    'Max Rang and Min Range cannot be same.' => '',
    'Max Rang cannot be less then Min Range.' => '',
    'Please add formula first.' => '',
    'Please enter a valid IFSC Length' => '',
    'Please enter valid ' => '',
    'Product is already added.' => '',
    'Product not found.' => '',
    'Purchase rate is already taken on this WEF Date.' => '',
    'State cannot be blank' => '',
    'Sub District cannot be blank' => '',
    'Union cannot be blank' => '',
    'Village cannot be blank' => '',
    'You have entered invalid email address.e.g. "abc@xyz.com"' => '',
    '{attribute} cannot be blank.' => '',
    '{attribute} must be a digit e.g. "11"' => '',
    '{attribute} must be a digit. e.g. "000001"' => '',
    '{attribute} must be a digit. e.g. "00001"' => '',
    '{attribute} must be a digit. e.g. "001"' => '',
    '{attribute} must be a digit. e.g. "01"' => '',
    '{attribute} must be a digit. e.g. "01".' => '',
    '{attribute} must be a digit. e.g. "15"' => '',
    '{attribute} must be a digit. e.g. "5"' => '',
    '{attribute} must be a digit. e.g. "5","5.5"' => '',
    '{attribute} must be a digit.e.g."123456"' => '',
    '{attribute} must be of  2 digit. e.g."01"' => '',
    '{attribute} must be of 3 digit. e.g."001"' => '',
    '{attribute} must be of 5 digit. e.g."00001"' => '',
    '{attribute} must be of 6 digit. e.g."000001"' => '',
    '{attribute} must contain 6 digit ' => '',
    'Entered A/C No already exists.' => '@@@@',
    '{attribute} must be a numeric.' => '@@@@',
    '{attribute} should contain at least 6 characters.' => '@@@@',
];
