<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Local Name' => 'Hindi Name',
    'Union' => 'Company',
    'PCDF' => 'EVEREST',
    'Union Code' => 'Company Code',
    'Old Union Code' => 'Old Company Code',
    'Union Name' => 'Company Name',
    'Union Short Name' => 'Company Short Name',
    'Add New Union District' => 'Add New Company District',
    'Union Districts for' => 'Company Districts for',
    'Select Union' => 'Select Company',
    '201 - Union Collection Report List' => '201 - Company Collection Report List',
    '210 - Union-Day Crosstab List' => '210 - Company-Day Crosstab List',
    'Union Name' => 'Company Name',
    'Union Credit' => 'Company Credit',
    'Union Credit Limit List' => 'Company Credit Limit List',
    'Union Credit Limit' => 'Company Credit Limit',
    'Add New Union Credit Limit' => 'Add New Company Credit Limit',
];
